name: Daily YouTube Upload

on:
  schedule:
    - cron: '0 9 * * *'  # Every day at 9:00 UTC
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install FFmpeg, ImageMagick, and fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick fonts-dejavu

      - name: Debug ImageMagick policy before changes
        run: |
          echo "ImageMagick policy before changes:"
          cat /etc/ImageMagick-6/policy.xml || echo "Policy file not found"

      - name: Configure ImageMagick policy
        run: |
          sudo sed -i 's/<policy domain="coder" rights="none" pattern="TEXT" \/>/<policy domain="coder" rights="read|write" pattern="TEXT" \/>/' /etc/ImageMagick-6/policy.xml || true
          sudo sed -i 's/<policy domain="path" rights="none" pattern="@\*" \/>/<policy domain="path" rights="read|write" pattern="@*" \/>/' /etc/ImageMagick-6/policy.xml || true
          sudo sed -i '/<policy domain="path" rights="none" pattern="@\*" \/>/d' /etc/ImageMagick-6/policy.xml || true
          echo '<policy domain="path" rights="read|write" pattern="@*" />' | sudo tee -a /etc/ImageMagick-6/policy.xml

      - name: Debug ImageMagick policy after changes
        run: |
          echo "ImageMagick policy after changes:"
          cat /etc/ImageMagick-6/policy.xml

      - name: Verify FFmpeg and ImageMagick
        run: |
          ffmpeg -version
          convert -version
          echo "IMAGEMAGICK_BINARY: $IMAGEMAGICK_BINARY"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --force-reinstall moviepy==1.0.3 google-auth google-auth-oauthlib google-api-python-client numpy==1.24.3 elevenlabs==2.3.0

      - name: Verify moviepy installation
        run: python3 -m pip show moviepy

      - name: Test MoviePy import
        run: python3 -c "from moviepy.editor import VideoFileClip; print('MoviePy imported successfully')"

      - name: List installed packages and Python path
        run: |
          python3 -m pip list
          python3 -c "import sys; print(sys.executable); print(sys.path)"

      - name: Generate video
        env:
          COMMUNITY_LANGUAGE: en
          IMAGEMAGICK_BINARY: /usr/bin/convert
          ELEVEN_API_KEY: ${{ secrets.ELEVEN_API_KEY }}
        run: /usr/bin/env python3 generate_video.py

      - name: Check generated video
        run: |
          ls -lh output_video.mp4
          file output_video.mp4

      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-video
          path: output_video.mp4
          if-no-files-found: error

      - name: Upload to YouTube
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        run: /usr/bin/env python3 upload_to_youtube.py
