name: Daily YouTube Upload

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9:00 UTC
  workflow_dispatch:      # Enables manual runs from GitHub UI

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install moviepy gTTS google-auth google-auth-oauthlib google-api-python-client

      - name: Verify moviepy installation
        run: pip show moviepy

      - name: Generate video
        env:
          COMMUNITY_LANGUAGE: en  # or fr
        run: python generate_video.py

      - name: Upload to YouTube
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        run: python upload_to_youtube.py
