name: Daily YouTube Upload

on:
  schedule:
    - cron: '0 9 * * *'  # Every day at 9:00 UTC
  workflow_dispatch:      # Manual trigger support

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install moviepy gTTS google-auth google-auth-oauthlib google-api-python-client

      - name: Verify moviepy installation
        run: python3 -m pip show moviepy

      - name: List installed packages and Python path
        run: |
          python3 -m pip list
          python3 -c "import sys; print(sys.executable); print(sys.path)"

      - name: Generate video
        env:
          COMMUNITY_LANGUAGE: en  # Change to 'fr' for French learners
        run: python3 generate_video.py

      - name: Upload to YouTube
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        run: python3 upload_to_youtube.py
 YouTube
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        run: python3 upload_to_youtube.py
